services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        environment:
            - GIN_MODE=release
        volumes:
            - ./backend/data:/app/data

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - VITE_API_URL=http://backend:8080
        depends_on:
            - backend
