version: "2"
run:
    tests: false
linters:
    default: none
    enable:
        - bodyclose
        - dogsled
        - dupl
        - errcheck
        - errorlint
        - funlen
        - gocheckcompilerdirectives
        - gochecknoinits
        - goconst
        - gocritic
        - gocyclo
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - lll
        - loggercheck
        - mnd
        - modernize
        - nakedret
        - nilerr
        - nilnil
        - noctx
        - nolintlint
        - revive
        - rowserrcheck
        - sloglint
        - staticcheck
        - sqlclosecheck
        - tagalign
        - tagliatelle
        - unconvert
        - unparam
        - unused
        - whitespace
    settings:
        errorlint:
            asserts: false
        funlen:
            lines: 200
            statements: 60
            ignore-comments: true
        goconst:
            min-len: 3
            min-occurrences: 3
        gocritic:
            enabled-tags:
                - diagnostic
                - experimental
                - opinionated
                - performance
                - style
        gocyclo:
            min-complexity: 15
        gosec:
            excludes:
                - G101
        lll:
            line-length: 300
        mnd:
            checks:
                - argument
                - case
                - condition
                - return
            ignored-functions:
                - byte
        nolintlint:
            require-explanation: false
            require-specific: false
            allow-unused: false
        revive:
            rules:
                - name: unexported-return
                  disabled: true
                - name: unused-parameter
        tagalign:
            order:
                - json
                - db
                - validate
            strict: true
        tagliatelle:
            case:
                rules:
                    json: snake
    exclusions:
        generated: lax
        presets:
            - comments
            - common-false-positives
            - legacy
            - std-error-handling
        rules:
            - linters:
                  - mnd
              path: _test\.go
        paths:
            - .*_templ\.go$
formatters:
    enable:
        - gofmt
        - goimports
    settings:
        gofmt:
            rewrite-rules:
                - pattern: interface{}
                  replacement: any
    exclusions:
        generated: lax
        paths:
            - .*_templ\.go$
            - third_party$
            - builtin$
            - examples$
